### ISSUE TITLE
[Bug]: PRIMARY KEY and UNIQUE INDEX not always respected

### ISSUE THREAD

**Issue by breml** [hydradatabase/hydra#177]
### What's wrong?

I use the latest container version of hydra (https://github.com/orgs/hydradatabase/packages/container/hydra/139632640?tag=14-22e7434a7e34d12a57a346e5d6c1d74da75f5046).

I have a simple columnar table containing metric data. This data consists of multiple `varchar` fields (basically segments of the identifier of the metric) and a `float8` value.
I was looking for a way to prevent duplicate insertion of the same metric. Therefore I added an other column containing an `int8` value, which is a 64-bit hash of the `varchar` fields (concatenated) mentioned above. My idea was to set a `primary key` or `unique index` on the `int8` column to prevent multiple inserts for the same metric.

Unfortunately, this did not work out as expected. I add ~40000 metric with `copy from`. Then I wait a little bit and run the same `copy from` again. Sometimes it fails (with key violation, as expected), sometimes it is successful. After successful runs, I can verify the result by querying for one of the hash values and I do get back two (or more, if I ran the `copy from` more than 2 times) identical rows, which should by definition not be possible (also the size of the table does increase, so cleary the data has been stored multiple times).

This leads me to two questions:

1. Is this expected behavior or is this a bug?
2. What is the recommended way with Hydra to prevent duplicate entries (what a `primary key` would normally guarantee)?

**Comment by JerrySievert** [comment]
hi @breml,

are you able to provide a sample schema and constraints (create statements) that you are able to reproduce this on?  that would help quite a bit!

thanks

**Comment by breml** [comment]
Hi @JerrySievert 

The DB schema looks like this (with primary key):

```sql
CREATE TABLE metric (
	hash int8 NOT NULL,
	key_part1 varchar NOT NULL,
	key_part2 varchar NOT NULL,
	key_part3 varchar,
	key_part4 varchar,
	key_part5 varchar,
	key_part6 varchar,
	key_part7 varchar,
	value float8 NOT NULL,
	PRIMARY KEY (hash)
) USING columnar;
```

and with unique key:

```sql
CREATE TABLE metric (
	hash int8 NOT NULL,
	key_part1 varchar NOT NULL,
	key_part2 varchar NOT NULL,
	key_part3 varchar,
	key_part4 varchar,
	key_part5 varchar,
	key_part6 varchar,
	key_part7 varchar,
	value float8 NOT NULL,
) USING columnar;
CREATE UNIQUE INDEX unique_metrics_idx ON metric (hash);
```

In both cases, I observed the same behavior. The value for `murmur_hash` is calculated externally from the DB on the application side. The hash is formed on the concatenated string (separated by a separator) of all the fields except the value (see below pseudo code):

```
hash(join([]strings{key_part1, key_part2, key_part3, key_part4, key_part5, key_part6, key_part7}, separator))
```

The data is inserted in batches with `copy from`. For now I work with a small data set of ~40k rows. After the initial data load, I retried. Sometimes all batches fail on the second run (expected), sometimes only some batches fail (not expected), sometimes all batches are re-added successfully (not expected). In the "failing" cases, I can see, that the additional data is in fact in the table and that I get multiple rows with the same value for `hash` even though there is a primary key / unique key constraint set on `hash`.
In both scenarios I observed,

**Comment by JerrySievert** [comment]
if I'm reading this correctly, you're generating `insert` statements in your application that are then being run as `\copy from`?

is there any chance you have an example of the failure specifically that you can share?

**Comment by breml** [comment]
I think, there are no `insert` statements involved. The application is written in Go and I am using `github.com/jackc/pgx/v5` as the DB driver. I am using the `pgx.CopyFromRows` function, which basically reads from a 2-dimensional slice (array) in memory. The DB driver is using the `PGCOPY\n\377\r\n\000` sequence (https://github.com/jackc/pgx/blob/master/copy_from.go#L143), so I guess this `COPY` is used (see https://www.postgresql.org/docs/current/sql-copy.html, section Binary Format).

**Comment by JerrySievert** [comment]
I've tried to break it down to its constituent pieces:

```
CREATE TABLE metric (
  hash int8 NOT NULL,
  PRIMARY KEY(hash)
);
```

```
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/jackc/pgx/v5"
)

func main() {
	// urlExample := "postgres://username:password@localhost:5432/database_name"
	conn, err := pgx.Connect(context.Background(), os.Getenv("DATABASE_URL"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(context.Background())

	rows := [][]interface{}{
		{int32(36)},
		{int32(29)},
		{int32(36)},
		{int32(29)},
		{int32(36)},
		{int32(29)},
		{int32(36)},
		{int32(29)},
		{int32(36)},
		{int32(29)},
		{int32(36)},
		{int32(29)},
		{int32(36)},
		{int32(29)},
		{int32(36)},
		{int32(29)},
		{int32(36)},
		{int32(29)},
	}

	copyCount, err := conn.CopyFrom(
		context.Background(),
		pgx.Identifier{"metric"},
		[]string{"hash"},
		pgx.CopyFromRows(rows),
	)

	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stdout, "%d rows copied\n", copyCount)
}
```

but while `copy` relaxes some constraints (`CHECK` specifically), it does not remove uniqueness, and I have not been able to make it fail on `heap` nor `columnar` tables.


are you able to provide a reproduction of the issue, as I apparently am not able to reproduce locally?

**Comment by breml** [comment]
Hi @JerrySievert 

Thanks for the minimal example. With your code, I am not able to produce the issue (more about why I think this is the case further down).
I already worked on something similar. I now have an example, that fails reproducible on my setup (more about the setup further down, since now I think there might be some relevance).

### Go Code

```golang
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strconv"

	"github.com/brianvoe/gofakeit/v6"
	"github.com/jackc/pgx/v5"
	"github.com/spaolacci/murmur3"
)

var (
	dropTable            = flag.Bool("drop", false, "drop the table before creating it")
	createTablePK        = flag.Bool("create-table-pk", false, "create the table with pk before inserting")
	createTableUniqueKey = flag.Bool("create-table-unique-key", false, "create the table with unique key before inserting")
	rows                 = flag.Int("rows", 1000, "number of rows per batch to insert")
)

func main() {
	flag.Parse()

	ctx := context.Background()
	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	die(err)
	defer conn.Close(ctx)

	if *dropTable {
		_, err = conn.Exec(ctx, "drop table if exists metric;")
		die(err)
	}

	if *createTablePK {
		_, err = conn.Exec(ctx, `CREATE EXTENSION IF NOT EXISTS columnar;`)
		die(err)
		_, err = conn.Exec(ctx, `create table if not exists metric (
				hash int8 NOT NULL,
				key_part1 varchar NOT NULL,
				key_part2 varchar NOT NULL,
				value float8 NOT NULL,
				key_part3 varchar,
				key_part4 varchar,
				key_part5 varchar,
				key_part6 varchar,
				key_part7 varchar,
				PRIMARY KEY (hash)
			) USING columnar;`)
		die(err)
	}

	if *createTableUniqueKey {
		_, err = conn.Exec(ctx, `CREATE EXTENSION IF NOT EXISTS columnar;`)
		die(err)
		_, err = conn.Exec(ctx, `create table if not exists metric (
				hash int8 NOT NULL,
				key_part1 varchar NOT NULL,
				key_part2 varchar NOT NULL,
				value float8 NOT NULL,
				key_part3 varchar,
				key_part4 varchar,
				key_part5 varchar,
				key_part6 varchar,
				key_part7 varchar
			) USING columnar;`)
		die(err)
		_, err = conn.Exec(ctx, `CREATE UNIQUE INDEX unique_metrics_idx ON metric (hash);`)
		die(err)
	}

	if len(flag.Args()) != 1 {
		fmt.Fprintf(os.Stderr, "Usage: %s <offset>\n", os.Args[0])
		os.Exit(1)
	}

	offset, err := strconv.Atoi(flag.Args()[0])
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to convert offset to int: %v\n", err)
		os.Exit(1)
	}

	idx := offset * *rows
	key_elements := []string{"aaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "cccccccccccccccccccccc", "ddddddddd", "eeeeeeeeeeeeeee", "fffff", "gggg", "hhhhhhhhhhhhhhhhh", "iiiiiiiii", "jjjjjjjjjjjjjjjjjjjjjj"}

	metricRows := make([][]any, 0, *rows)
	for row := 0; row < *rows; row++ {
		key_part1 := key_elements[idx%10]
		key_part2 := key_elements[(idx/10)%10]
		key_part3 := key_elements[(idx/100)%10]
		key_part4 := key_elements[(idx/1000)%10]
		key_part5 := key_elements[(idx/10000)%10]
		key_part6 := key_elements[(idx/100000)%10]
		key_part7 := key_elements[(idx/1000000)%10]

		metricRow := []any{
			hash(key_part1, key_part2, key_part3, key_part4, key_part5, key_part6, key_part7),
			key_part1,
			key_part2,
			float64(gofakeit.Number(0, 100)),
			key_part3,
			key_part4,
			key_part5,
			key_part6,
			key_part7,
		}
		metricRows = append(metricRows, metricRow)
		idx++
	}

	_, err = conn.CopyFrom(
		ctx,
		pgx.Identifier{"metric"},
		[]string{
			"hash",
			"key_part1",
			"key_part2",
			"value",
			"key_part3",
			"key_part4",
			"key_part5",
			"key_part6",
			"key_part7",
		},
		pgx.CopyFromRows(metricRows),
	)
	if err != nil {
		fmt.Printf("failed: %v\n", err)
	}
}

func hash(key_part1, key_part2, key_part3, key_part4, key_part5, key_part6, key_part7 string) int {
	separator := []byte{124}

	hasher := murmur3.New64()
	hasher.Write([]byte(key_part1))
	hasher.Write(separator)
	hasher.Write([]byte(key_part2))
	hasher.Write(separator)
	hasher.Write([]byte(key_part3))
	hasher.Write(separator)
	hasher.Write([]byte(key_part4))
	hasher.Write(separator)
	hasher.Write([]byte(key_part5))
	hasher.Write(separator)
	hasher.Write([]byte(key_part6))
	hasher.Write(separator)
	hasher.Write([]byte(key_part7))

	return int(hasher.Sum64())
}

func die(err error) {
	if err != nil {
		panic(err)
	}
}
```

It might be possible to strip the example further down, but I did not yet try to do so.

### Execution

Execution (fish shell syntax):
What this basically does is:
* drop table
* create table with pk
* insert with offset 0
* loop 10 times, insert with offsets 1 to 10
* again loop 10 times, insert with offsets 1 to 10

Based on the bellows output, it successfully inserts for offset 1 to 5 a second time and only starting from offset 6, the constraint starts to kick in.

```fish
$ go run ./cmd/pocs/hydra_pk_issue_177 -drop -create-table-pk 0; for i in (seq 1 10); echo $i; go run ./cmd/pocs/hydra_pk_issue_177/ $i; end; for i in (seq 1 10); echo $i; go run ./cmd/pocs/hydra_pk_issue_177/ $i; end
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
failed: ERROR: duplicate key value violates unique constraint "metric_pkey1" (SQLSTATE 23505)
7
failed: ERROR: duplicate key value violates unique constraint "metric_pkey1" (SQLSTATE 23505)
8
failed: ERROR: duplicate key value violates unique constraint "metric_pkey1" (SQLSTATE 23505)
9
failed: ERROR: duplicate key value violates unique constraint "metric_pkey1" (SQLSTATE 23505)
10
failed: ERROR: duplicate key value violates unique constraint "metric_pkey1" (SQLSTATE 23505)
```

*To me, this looks like a race condition and more specifically, the race condition seams to be related to different DB connections.*

### Setup

The hydra container (version mentioned in previous comment) is running on a "rather" slow server (AMD Embedded R-Series RX-421BD Radeon R7; 4 cores; 20 GB RAM) and the data is stored on spinning discs (not SSD). I use this system for my lab work. The above Go program is executed on my notebook and the connection to the server is going of the network.

The reason why I am mentioning this is, that with a rather slow system it might be "easier" to hit such race conditions.

Additionally, I played with some of the "parameters". For example if I reduce all the key parts to single letter ("a", "b", etc.), the test does not fail (meaning the duplicate key does kick in immediately). Also if I reduce the size of each batch from 1000 to e.g. 100, it does no longer fail. I also played with the `unique key` constraint and this one behaves somewhat differently. I was not yet able to find a configuration that fails with the above code (but with my real code I do see the issue).
So again, this might be related to the setup, more specifically to the spinning disk, which take some time to persist the data (but this is just wild guessing).


I hope, you find these additional details helpful.

**Comment by breml** [comment]
Just as an addition, I simplified the program a little bit, such that there is just one `data` column instead of 7 key parts.
In this case, I need to add 20000 bytes per row to trigger the failing state (instead of ~200 bytes spread among 7 columns):

```golang
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/spaolacci/murmur3"
)

var (
	dropTable            = flag.Bool("drop", false, "drop the table before creating it")
	createTablePK        = flag.Bool("create-table-pk", false, "create the table with pk before inserting")
	createTableUniqueKey = flag.Bool("create-table-unique-key", false, "create the table with unique key before inserting")
	rows                 = flag.Int("rows", 1000, "number of rows per batch to insert")
	dataBytes            = flag.Int("data-bytes", 20000, "number of data bytes to insert")
)

func main() {
	flag.Parse()

	ctx := context.Background()
	conn, err := pgx.Connect(ctx, os.Getenv("DATABASE_URL"))
	die(err)
	defer conn.Close(ctx)

	if *dropTable {
		_, err = conn.Exec(ctx, "drop table if exists metric;")
		die(err)
	}

	if *createTablePK {
		_, err = conn.Exec(ctx, `CREATE EXTENSION IF NOT EXISTS columnar;`)
		die(err)
		_, err = conn.Exec(ctx, `create table if not exists metric (
				hash int8 NOT NULL,
				data varchar,
				PRIMARY KEY (hash)
			) USING columnar;`)
		die(err)
	}

	if *createTableUniqueKey {
		_, err = conn.Exec(ctx, `CREATE EXTENSION IF NOT EXISTS columnar;`)
		die(err)
		_, err = conn.Exec(ctx, `create table if not exists metric (
				hash int8 NOT NULL,
				data varchar,
			) USING columnar;`)
		die(err)
		_, err = conn.Exec(ctx, `CREATE UNIQUE INDEX unique_metrics_idx ON metric (hash);`)
		die(err)
	}

	if len(flag.Args()) != 1 {
		fmt.Fprintf(os.Stderr, "Usage: %s <offset>\n", os.Args[0])
		os.Exit(1)
	}

	offset, err := strconv.Atoi(flag.Args()[0])
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to convert offset to int: %v\n", err)
		os.Exit(1)
	}

	idx := offset * *rows
	data := strings.Repeat("a", *dataBytes)

	metricRows := make([][]any, 0, *rows)
	for row := 0; row < *rows; row++ {
		metricRow := []any{
			hash(strconv.Itoa(idx)),
			data,
		}
		metricRows = append(metricRows, metricRow)
		idx++
	}

	_, err = conn.CopyFrom(
		ctx,
		pgx.Identifier{"metric"},
		[]string{
			"hash",
			"data",
		},
		pgx.CopyFromRows(metricRows),
	)
	if err != nil {
		fmt.Printf("failed: %v\n", err)
	}
}

func hash(key string) int {
	hasher := murmur3.New64()
	hasher.Write([]byte(key))

	return int(hasher.Sum64())
}

func die(err error) {
	if err != nil {
		panic(err)
	}
}
```

Execution ():

```fish
$ go run ./cmd/pocs/hydra_pk_issue_177 -drop -create-table-pk 0; for i in (seq 1 10); echo $i; go run ./cmd/pocs/hydra_pk_issue_177/ $i; end; for i in (seq 1 10); echo $i; go run ./cmd/pocs/hydra_pk_issue_177/ $i; end
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
failed: ERROR: duplicate key value violates unique constraint "metric_pkey1" (SQLSTATE 23505)
10
failed: ERROR: duplicate key value violates unique constraint "metric_pkey1" (SQLSTATE 23505)
```

**Comment by JerrySievert** [comment]
I was able to reproduce, thank you!


but, your hypothesis about it being because of system speed is not accurate, I was able to reproduce it on my fastest machine with my fastest nvme.  I'll try to hunt down the reasons and get a fix out as soon as I can.

**Comment by breml** [comment]
Very good, I am glad you could reproduce the issue.

About the system speed was just an assumption that it is more likely to trigger the issue than on fast machines. But in the end it does not matter to me if this assumption was correct or not, the only thing that matters is, that the issue can be reproduced and finally fixed. I look forward to a fixed version of this.

**Comment by JerrySievert** [comment]
to put it more succinctly, on a multi-insert (like `copy`), it was only doing a constraint check on creation of a new stripe.

**Comment by JerrySievert** [comment]
I've merged #182 which fixes this - so closing.

docker image should now be updated as well.

**Comment by breml** [comment]
@JerrySievert Unfortunately, the latest version does not seem to fix the issue completely.

I use image `ghcr.io/hydradatabase/hydra:latest`, which resolves to

```shell
$ kubectl get pod hydra -o json | jq '.status.containerStatuses[0].imageID'
"ghcr.io/hydradatabase/hydra@sha256:9d062d8884af7a3502e7ad6ac640bac989a76c13aff84d8228cbfb4a5d1ec606"
```

If I execute the above mentioned program again, it got better, since it does no longer fail on every run, but I still observed, that it failed some times. For example I got the following outputs:

```none
$ go run ./cmd/pocs/hydra_pk_issue_177 -drop -create-table-pk 0; for i in (seq 1 10); echo $i; go run ./cmd/pocs/hydra_pk_issue_177/ $i; end; for i in (seq 1 10); echo $i; go run ./cmd/pocs/hydra_pk_issue_177/ 
$i; end                                                                                                                                                                                                                                       
1                                                                                                                      
2                                                                                                                      
3                                                                                                                      
4                                                                                                                      
5                            
6                                                                                                                      
7                                                                                                                      
8                                                                                                                      
9                                                                                                                                                                                                                                             
10                                                                                                                     
1    
2                                                                                                                      
3                       
4                                                                                                                      
5                                                                                                                      
failed: ERROR: duplicate key value violates unique constraint "metric_pkey" (SQLSTATE 23505)                           
6                                                                                                                      
failed: ERROR: duplicate key value violates unique constraint "metric_pkey" (SQLSTATE 23505)                           
7                     
failed: ERROR: duplicate key value violates unique constraint "metric_pkey" (SQLSTATE 23505)                           
8                       
failed: ERROR: duplicate key value violates unique constraint "metric_pkey" (SQLSTATE 23505)                           
9                                      
failed: ERROR: duplicate key value violates unique constraint "metric_pkey" (SQLSTATE 23505)                                                                                                                                                  10                                           
failed: ERROR: duplicate key value violates unique constraint "metric_pkey" (SQLSTATE 23505)
```

and also:

```none
$ go run ./cmd/pocs/hydra_pk_issue_177 -drop -create-table-pk 0; for i in (seq 1 10); echo $i; go run ./cmd/pocs/hydra_pk_issue_177/ $i; end; for i in (seq 1 10); echo $i; go run ./cmd/pocs/hydra_pk_issue_177/ $i; end
1
2
3
4
5
6
7
8
9
10
1
failed: ERROR: duplicate key value violates unique constraint "metric_pkey" (SQLSTATE 23505)
2
failed: ERROR: duplicate key value violates unique constraint "metric_pkey" (SQLSTATE 23505)
3
4
5
6
7
8
9
10
```

Side question: Is there an easy way to get the version of hydra with SQL, sucht that I can get the version always as first call in my tests to make sure, that the container is updated successfully?

**Comment by wuputah** [comment]
I'd recommend pulling explicit tags, e.g. `ghcr.io/hydradatabase/hydra:14-22d647ed4062184698b3a1fa8b37e1cef6ddaff7` to make sure you are using a specific version. These tags correspond to the Postgres and git commit of the build.
